name: Deploy

on:
  # Automatically trigger on push to the canary branch
  push:
    branches: ['canary']

  # Still allow manual dispatch with flavor selection
  workflow_dispatch:
    inputs:
      flavor:
        description: 'Select what environment to deploy to'
        type: choice
        default: canary
        options:
          - canary
          - beta
          - stable
          - internal

permissions:
  contents: 'write'
  id-token: 'write'
  packages: 'write'

jobs:
  server-deploy:
    name: Deploy to Self-Hosted Server
    # This condition ensures the job runs if:
    # 1) It's a push event to the 'canary' branch, OR
    # 2) It's a manual workflow_dispatch with flavor == 'canary'
    if: >
      (github.event_name == 'push' && github.ref == 'refs/heads/canary')
      || (github.event_name == 'workflow_dispatch' && github.event.inputs.flavor == 'canary')

    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # Use appleboy/ssh-action to SSH into your DigitalOcean droplet,
      # pull the code, and run Docker Compose.
      - name: SSH to Server & Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }} # e.g., your droplet IP
          username: ${{ secrets.SERVER_USER }} # e.g., root
          key: ${{ secrets.SSH_PRIVATE_KEY }} # private key from GitHub Secrets
          script_stop: false
          script: |
            # Example commands to deploy your AFFiNE code
            cd /var/www/app/yaumy
            git pull origin canary
            cd .docker/selfhost
            docker compose -f compose.yml up -d --build
