name: Deploy

on:
  workflow_dispatch:
    inputs:
      flavor:
        description: 'Select what environment to deploy to'
        type: choice
        default: canary
        options:
          - canary
          - beta
          - stable
          - internal

permissions:
  contents: 'write'
  id-token: 'write'
  packages: 'write'

###############################################################################
# REMOVED / COMMENTED GCP-JOBS
# (No more "Output previous version," "Build Images," "Deploy," or "deploy-done")
# because they reference GCP cluster-auth, and cause errors if you aren't using GCP.
###############################################################################
#
# jobs:
#   output-prev-version:
#     name: Output previous version
#     runs-on: ubuntu-latest
#     environment: ${{ github.event.inputs.flavor }}
#     ...
#
#   build-images:
#     name: Build Images
#     ...
#
#   deploy:
#     name: Deploy to cluster
#     ...
#
#   deploy-done:
#     name: Post deploy message
#     ...

###############################################################################
# NEW JOB: Deploy to your self-hosted server via SSH (only if canary)
###############################################################################
jobs:
  server-deploy:
    name: Deploy to Self-Hosted Server
    # By default, we only do this if the flavor is canary. Adjust if needed.
    if: ${{ github.event.inputs.flavor == 'canary' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # This uses appleboy/ssh-action to log into your DigitalOcean droplet,
      # pull the code, and run Docker Compose.
      - name: SSH to Server & Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }} # e.g., your droplet IP
          username: ${{ secrets.SERVER_USER }} # e.g., root
          key: ${{ secrets.SSH_PRIVATE_KEY }} # private key from GitHub Secrets
          script_stop: false
          script: |
            # Example commands to deploy your AFFiNE code
            cd /var/www/app/yaumy
            git pull origin canary
            cd .docker/selfhost
            docker compose -f compose.yml up -d --build
